<!-- Navigation PHP Include -->
<nav class="z-depth-0 blue-grey lighten-2">
	<div class="nav-container nav-wrapper">
		<a href="index.php" class="home-link-left">Home</a>
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i>
		<ul class="right hide-on-med-and-down">
			<li><a href="johndenzer.php">John Denzer</a></li>
			<li><a href="alihashim.php">Ali Hashim</a></li>
			<li><a href="aaronraymond.php">Aaron Raymond</a></li>
		</ul>
		<ul class="side-nav" id="mobile-demo">
			<li><a href="johndenzer.php">John Denzer</a></li>
			<li><a href="alihashim.php">Ali Hashim</a></li>
			<li><a href="aaronraymond.php">Aaron Raymond</a></li>
		</ul>
	</div>
</nav>