<!DOCTYPE html>
<html lang="en">
<head>

	<!-- Importing fonts -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!-- Importing materialize css (minimized) -->
	<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen">
	<!-- Importing override file -->
	<link href="css/overrides.css" type="text/css" rel="stylesheet" media="screen">
	<!-- Setting viewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<title><?php echo $title ?></title>

</head>

<body>